name: ethio_app
description: ETHIO Flutter starter combined package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.0.0
  firebase_messaging: ^14.4.0
  provider: ^6.0.5
  image_picker: ^0.8.7+4
  flutter_image_compress: ^1.1.0
  uuid: ^3.0.7
  lottie: ^2.3.0
  connectivity_plus: ^4.0.0
  flutter_local_notifications: ^12.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/ethio_splash.json
